import { TOPOLOGY_VISUAL_FRAGMENT } from "./topology-visuals.ts";

export const TOPOLOGY_CONTROLLER_FRAGMENT = `
  const topologyPanel = document.getElementById("panel-topology");
  const topology = model.topology || { modes: [], worktrees: [], events: [], unavailable: {} };
  const panModes = ["metro", "timeline", "gittree", "swimlanes"];
  let topologyMode = "metro"; let topologyScale = 1; let topologyX = 0; let topologyY = 0;
  const topologyModes = Array.isArray(topology.modes) ? topology.modes : [];
  const topologyNote = () => { const note = document.createElement("p"); note.className = "section-note"; const unavailable = topology.unavailable || {}; note.textContent = topologyMode === "gittree" ? unavailable.gitTree : topologyMode === "radar" ? unavailable.radar : topologyMode === "sunburst" ? unavailable.sunburst : topologyMode === "timeline" ? unavailable.timeline : topologyMode === "swimlanes" ? unavailable.swimlanes : "Unverified relationship. Terminal alternative below exposes the same observed facts."; return note; };
  const topologyViewport = (drawing) => { const viewport = svg("g"); viewport.id = "topology-viewport"; viewport.setAttribute("transform", "translate(" + topologyX + "," + topologyY + ") scale(" + topologyScale + ")"); drawing.append(viewport); return viewport; };
${TOPOLOGY_VISUAL_FRAGMENT}
  const topologyControls = () => { const controls = document.createElement("div"); controls.className = "topology-controls"; if (!panModes.includes(topologyMode)) return controls; [["topology-zoom-in", "+", "Zoom in topology"], ["topology-zoom-out", "-", "Zoom out topology"], ["topology-reset", "Reset", "Reset topology view"]].forEach(([id, text, description]) => { const button = document.createElement("button"); button.id = id; button.type = "button"; button.textContent = text; button.setAttribute("aria-label", description); button.addEventListener("click", () => { if (id === "topology-reset") { topologyScale = 1; topologyX = 0; topologyY = 0; } else topologyScale = Math.max(0.4, Math.min(4, topologyScale * (id === "topology-zoom-in" ? 1.25 : 0.8))); renderTopology(); document.getElementById(id)?.focus(); }); controls.append(button); }); return controls; };
  const renderTopology = () => { if (!topologyPanel) return; topologyPanel.replaceChildren(); const card = document.createElement("section"); card.className = "card topology-card"; const heading = document.createElement("h2"); heading.textContent = "Observed Topology"; const announcement = document.createElement("p"); announcement.className = "visually-hidden"; announcement.setAttribute("aria-live", "polite"); announcement.textContent = "Topology mode: " + topologyMode; const selector = document.createElement("div"); selector.id = "topology-mode-selector"; selector.setAttribute("role", "radiogroup"); selector.setAttribute("aria-label", "Topology mode"); topologyModes.forEach((mode) => { const button = document.createElement("button"); button.type = "button"; button.setAttribute("role", "radio"); button.setAttribute("data-topology-mode", mode); button.setAttribute("aria-checked", String(mode === topologyMode)); button.setAttribute("tabindex", mode === topologyMode ? "0" : "-1"); button.textContent = mode; const selectMode = () => { topologyMode = mode; topologyScale = 1; topologyX = 0; topologyY = 0; renderTopology(); document.querySelector("[data-topology-mode=" + mode + "]")?.focus(); }; button.addEventListener("click", selectMode); button.addEventListener("keydown", (event) => { const index = topologyModes.indexOf(mode); const next = event.key === "ArrowRight" ? topologyModes[(index + 1) % topologyModes.length] : event.key === "ArrowLeft" ? topologyModes[(index + topologyModes.length - 1) % topologyModes.length] : event.key === "Home" ? topologyModes[0] : event.key === "End" ? topologyModes[topologyModes.length - 1] : null; if (next) { event.preventDefault(); topologyMode = next; topologyScale = 1; topologyX = 0; topologyY = 0; renderTopology(); document.querySelector("[data-topology-mode=" + next + "]")?.focus(); } }); selector.append(button); }); card.append(heading, announcement, selector, topologyNote(), topologyControls()); const visual = topologyVisual(); if (topologyMode === "terminal") card.append(visual); else { const graphical = document.createElement("details"); graphical.className = "topology-graphic"; graphical.open = !(window.matchMedia && window.matchMedia("(max-width: 420px)").matches); const summary = document.createElement("summary"); summary.textContent = "Show graphical " + topologyMode + " view"; graphical.append(summary, visual); card.append(topologyAlternative(), graphical); } topologyPanel.append(card); };
`;
