import { TOPOLOGY_VISUAL_FRAGMENT } from "./topology-visuals.ts";

export const TOPOLOGY_CONTROLLER_FRAGMENT = `
  const topologyPanel = document.getElementById("panel-topology");
  const topology = model.topology || { modes: [], worktrees: [], events: [], unavailable: {} };
  const panModes = ["metro", "timeline", "gittree", "swimlanes"];
  let topologyMode = "metro"; let topologyScale = 1; let topologyX = 0; let topologyY = 0;
  const topologyModes = Array.isArray(topology.modes) ? topology.modes : [];
  const compactTopologyAvailable = Boolean(window.matchMedia);
  const topologyModeLabel = (mode) => mode === "metro" ? "Metro Map" : mode === "radar" ? "Radar Scope" : mode === "gittree" ? "Git Tree" : mode.charAt(0).toUpperCase() + mode.slice(1);
  const topologyNote = () => { const note = document.createElement("p"); note.className = "section-note"; const unavailable = topology.unavailable || {}; note.textContent = topologyMode === "gittree" ? unavailable.gitTree : topologyMode === "radar" ? unavailable.radar : topologyMode === "sunburst" ? unavailable.sunburst : topologyMode === "timeline" ? unavailable.timeline : topologyMode === "swimlanes" ? unavailable.swimlanes : "Unverified relationship. Terminal alternative below exposes the same observed facts."; return note; };
  const topologyViewport = (drawing) => { const viewport = svg("g"); viewport.id = "topology-viewport"; viewport.setAttribute("transform", "translate(" + topologyX + "," + topologyY + ") scale(" + topologyScale + ")"); drawing.append(viewport); return viewport; };
${TOPOLOGY_VISUAL_FRAGMENT}
  const topologyControls = () => { const controls = document.createElement("div"); controls.className = "topology-controls"; if (!panModes.includes(topologyMode)) return controls; [["topology-zoom-in", "+", "Zoom in topology"], ["topology-zoom-out", "-", "Zoom out topology"], ["topology-reset", "Reset", "Reset topology view"]].forEach(([id, text, description]) => { const button = document.createElement("button"); button.id = id; button.type = "button"; button.textContent = text; button.setAttribute("aria-label", description); button.addEventListener("click", () => { if (id === "topology-reset") { topologyScale = 1; topologyX = 0; topologyY = 0; } else topologyScale = Math.max(0.4, Math.min(4, topologyScale * (id === "topology-zoom-in" ? 1.25 : 0.8))); renderTopology(); document.getElementById(id)?.focus(); }); controls.append(button); }); return controls; };
  const topologyLegend = () => { const legend = document.createElement("div"); legend.className = "topology-legend"; legend.setAttribute("data-compact-topology", String(compactTopologyAvailable)); (topology.worktrees || []).forEach((worktree, index) => { const item = document.createElement("button"); item.type = "button"; item.className = "topology-legend-item"; item.setAttribute("data-topology-legend-worktree", worktree.id); const swatch = document.createElement("span"); swatch.className = "topology-line-swatch palette-" + (index % 5); const text = document.createElement("span"); text.textContent = "W" + (index + 1) + "  " + label(worktree); item.append(swatch, text); item.addEventListener("click", () => choose(worktree.id, item.id)); legend.append(item); }); return legend; };
  const topologyDetail = () => { const detail = document.createElement("div"); detail.className = "topology-detail"; const worktree = selected(); if (!worktree) { const empty = document.createElement("p"); empty.className = "section-note"; empty.textContent = "Hover or click an element to inspect."; detail.append(empty); return detail; } const heading = document.createElement("h3"); heading.textContent = label(worktree); detail.append(heading); [["Path", worktree.path], ["HEAD", worktree.head || "Unavailable"], ["State", worktree.state], ["Owner", worktree.owner.sessionId || "Unavailable"]].forEach(([name, value]) => { const row = document.createElement("div"); row.className = "topology-detail-row"; const key = document.createElement("span"); key.textContent = name; const output = document.createElement("code"); output.textContent = value; row.append(key, output); detail.append(row); }); return detail; };
  const renderTopology = () => {
    if (!topologyPanel) return; topologyPanel.replaceChildren();
    const container = document.createElement("div"); container.className = "topology-container";
    const header = document.createElement("header"); header.className = "topology-header"; const titleGroup = document.createElement("div"); const eyebrow = document.createElement("div"); eyebrow.className = "eyebrow"; eyebrow.textContent = "Worktree Lifecycle Map"; const title = document.createElement("h1"); title.textContent = "Git Topology"; titleGroup.append(eyebrow, title); const back = document.createElement("button"); back.type = "button"; back.className = "topology-back"; back.setAttribute("data-report-panel", "operations"); back.textContent = "← Worktree dashboard"; back.addEventListener("click", () => { const tab = document.getElementById("tab-operations"); if (tab) activate(tab, false); }); header.append(titleGroup, back);
    const subtitle = document.createElement("p"); subtitle.className = "topology-subtitle"; subtitle.textContent = "A multi-style view of observed worktrees. Unverified ancestry, chronology, and lifecycle facts remain explicitly unavailable.";
    const announcement = document.createElement("p"); announcement.className = "visually-hidden"; announcement.setAttribute("aria-live", "polite"); announcement.textContent = "Topology mode: " + topologyMode;
    const selector = document.createElement("div"); selector.id = "topology-mode-selector"; selector.className = "topology-view-tabs"; selector.setAttribute("role", "radiogroup"); selector.setAttribute("aria-label", "Topology mode"); topologyModes.forEach((mode) => { const button = document.createElement("button"); button.type = "button"; button.setAttribute("role", "radio"); button.setAttribute("data-topology-mode", mode); button.setAttribute("aria-checked", String(mode === topologyMode)); button.setAttribute("tabindex", mode === topologyMode ? "0" : "-1"); button.textContent = topologyModeLabel(mode); const selectMode = () => { topologyMode = mode; topologyScale = 1; topologyX = 0; topologyY = 0; renderTopology(); document.querySelector("[data-topology-mode=" + mode + "]")?.focus(); }; button.addEventListener("click", selectMode); button.addEventListener("keydown", (event) => { const index = topologyModes.indexOf(mode); const next = event.key === "ArrowRight" ? topologyModes[(index + 1) % topologyModes.length] : event.key === "ArrowLeft" ? topologyModes[(index + topologyModes.length - 1) % topologyModes.length] : event.key === "Home" ? topologyModes[0] : event.key === "End" ? topologyModes[topologyModes.length - 1] : null; if (next) { event.preventDefault(); topologyMode = next; topologyScale = 1; topologyX = 0; topologyY = 0; renderTopology(); document.querySelector("[data-topology-mode=" + next + "]")?.focus(); } }); selector.append(button); });
    const wrap = document.createElement("div"); wrap.className = "topology-wrap"; const visual = topologyVisual(); visual.append(topologyControls()); const panel = document.createElement("aside"); panel.className = "topology-panel"; const panelTitle = document.createElement("h2"); panelTitle.textContent = topologyMode === "metro" ? "Lines" : topologyModeLabel(topologyMode); panel.append(panelTitle, topologyLegend(), topologyDetail(), topologyNote()); if (topologyMode === "terminal") wrap.append(visual, panel); else { const graphical = document.createElement("details"); graphical.className = "topology-graphic"; graphical.open = true; const summary = document.createElement("summary"); summary.textContent = "Show graphical " + topologyMode + " view"; graphical.append(summary, visual); panel.append(topologyAlternative()); wrap.append(graphical, panel); }
    container.append(header, subtitle, announcement, selector, wrap); topologyPanel.append(container);
  };
`;
