export const TOPOLOGY_VISUAL_FRAGMENT = `
  const allObservedEvents = () => (topology.events || []).map((event, index) => ({ event, index })).sort((left, right) => (left.event.at || "~").localeCompare(right.event.at || "~") || left.index - right.index || left.event.sessionId.localeCompare(right.event.sessionId) || left.event.kind.localeCompare(right.event.kind));
  const observedEvents = () => allObservedEvents().slice(0, 64);
  const observedEventsCaption = () => { const omitted = Math.max(0, allObservedEvents().length - 64); return omitted ? "Observed events (64 shown, " + omitted + " omitted; complete data remains in Raw Data)" : "Observed events"; };
  const topologyText = () => {
    const container = document.createElement("div"); container.className = "topology-terminal";
    const table = document.createElement("table"); table.className = "topology-terminal-table";
    const caption = document.createElement("caption"); caption.textContent = "Observed worktree records";
    const head = document.createElement("thead"); const headers = document.createElement("tr");
    ["State", "Branch", "Path", "HEAD", "Owner/activity", "Action"].forEach((name) => { const item = document.createElement("th"); item.setAttribute("scope", "col"); item.textContent = name; headers.append(item); }); head.append(headers);
    const body = document.createElement("tbody");
    (topology.worktrees || []).forEach((worktree) => { const row = document.createElement("tr"); [["State", worktree.state], ["Branch", label(worktree)], ["Path", worktree.path], ["HEAD", worktree.head || "Unavailable"], ["Owner/activity", worktree.owner.sessionId || "Unavailable"]].forEach(([name, value]) => { const cell = document.createElement("td"); cell.setAttribute("data-label", name); cell.textContent = value; row.append(cell); }); const actionCell = document.createElement("td"); actionCell.setAttribute("data-label", "Action"); const action = document.createElement("button"); action.id = "topology-terminal-option-" + worktree.id; action.type = "button"; action.className = "topology-terminal-row topology-terminal-action"; action.setAttribute("data-topology-worktree", worktree.id); action.setAttribute("aria-pressed", String(selectionCommitted && worktree.id === selectedId)); action.textContent = selectionCommitted && worktree.id === selectedId ? "Selected" : "Select"; action.addEventListener("click", () => choose(worktree.id, action.id)); actionCell.append(action); row.append(actionCell); body.append(row); });
    table.append(caption, head, body);
    const eventTable = document.createElement("table"); eventTable.className = "topology-event-table";
    const eventCaption = document.createElement("caption"); eventCaption.textContent = observedEventsCaption();
    const eventHead = document.createElement("thead"); const eventHeaders = document.createElement("tr");
    ["Session", "Kind", "Timestamp", "Action/availability"].forEach((name) => { const item = document.createElement("th"); item.setAttribute("scope", "col"); item.textContent = name; eventHeaders.append(item); }); eventHead.append(eventHeaders);
    const eventBody = document.createElement("tbody");
    observedEvents().forEach(({ event }) => { const row = document.createElement("tr"); [["Session", event.sessionId], ["Kind", event.kind], ["Timestamp", event.at || "Unavailable"], ["Action/availability", event.action ? "Observed action available" : "Unavailable"]].forEach(([name, value]) => { const cell = document.createElement("td"); cell.setAttribute("data-label", name); cell.textContent = value; row.append(cell); }); eventBody.append(row); });
    eventTable.append(eventCaption, eventHead, eventBody); container.append(table, eventTable); return container;
  };
  const topologyVisualLabel = (items, worktree) => "W" + (items.indexOf(worktree) + 1);
  const topologyPaletteClass = (items, worktree) => "palette-" + Math.max(0, items.indexOf(worktree) % 5);
  const topologyNode = (viewport, items, worktree, x, y, labelOffset = 0, maxLabels = 12) => {
    const node = svg("g"); node.id = "topology-option-" + worktree.id; node.setAttribute("role", "button"); node.setAttribute("tabindex", "0"); node.setAttribute("aria-pressed", String(selectionCommitted && worktree.id === selectedId)); node.setAttribute("aria-label", label(worktree) + ", select observed worktree");
    const circle = svg("circle"); circle.setAttribute("cx", String(x)); circle.setAttribute("cy", String(y)); circle.setAttribute("r", selectionCommitted && worktree.id === selectedId ? "16" : "12"); circle.setAttribute("class", "topology-node " + worktree.tone + " " + topologyPaletteClass(items, worktree) + (selectionCommitted && worktree.id === selectedId ? " selected" : "")); node.append(circle);
    const labelIndex = items.indexOf(worktree); const labelEvery = Math.max(1, Math.ceil(items.length / maxLabels)); const labelsAreCapped = maxLabels < 12; const showLabel = labelIndex % labelEvery === 0 && (!labelsAreCapped || labelIndex / labelEvery < maxLabels) || !labelsAreCapped && labelIndex === items.length - 1;
    if (showLabel) { const text = svg("text"); text.setAttribute("x", String(x + labelOffset)); text.setAttribute("y", String(y + 25)); text.setAttribute("text-anchor", labelOffset ? "start" : "middle"); text.textContent = topologyVisualLabel(items, worktree); node.append(text); }
    node.addEventListener("click", () => choose(worktree.id, node.id)); node.addEventListener("keydown", (event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); choose(worktree.id, node.id); } }); viewport.append(node);
  };
  const topologyInteractiveGroup = (viewport, worktree, className) => { const group = svg("g"); group.id = "topology-option-" + worktree.id; group.setAttribute("class", className); group.setAttribute("role", "button"); group.setAttribute("tabindex", "0"); group.setAttribute("aria-pressed", String(selectionCommitted && worktree.id === selectedId)); group.setAttribute("aria-label", label(worktree) + ", select observed worktree"); group.addEventListener("click", () => choose(worktree.id, group.id)); group.addEventListener("keydown", (event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); choose(worktree.id, group.id); } }); viewport.append(group); return group; };
  const topologyLine = (viewport, className, x1, y1, x2, y2) => { const line = svg("line"); line.setAttribute("class", className); line.setAttribute("x1", String(x1)); line.setAttribute("y1", String(y1)); line.setAttribute("x2", String(x2)); line.setAttribute("y2", String(y2)); viewport.append(line); return line; };
  const topologyPath = (viewport, className, value) => { const path = svg("path"); path.setAttribute("class", className); path.setAttribute("d", value); viewport.append(path); return path; };
  const topologyRect = (viewport, className, x, y, width, height, radius = 0) => { const rect = svg("rect"); rect.setAttribute("class", className); rect.setAttribute("x", String(x)); rect.setAttribute("y", String(y)); rect.setAttribute("width", String(width)); rect.setAttribute("height", String(height)); if (radius) { rect.setAttribute("rx", String(radius)); rect.setAttribute("ry", String(radius)); } viewport.append(rect); return rect; };
  const topologyCaption = (viewport, className, value, x, y, anchor = "start") => { const text = svg("text"); text.setAttribute("class", className); text.setAttribute("x", String(x)); text.setAttribute("y", String(y)); text.setAttribute("text-anchor", anchor); text.textContent = value; viewport.append(text); return text; };
  const topologyTimes = (events) => { const values = events.map(({ event }) => Date.parse(event.at)).filter((value) => Number.isFinite(value)); const min = values.length ? Math.min(...values) : 0; const max = values.length ? Math.max(...values) : 0; const span = Math.max(1, max - min); return { values, min, max, x: (value) => 190 + ((value - min) / span) * 520 }; };
  const topologyAnnularSector = (cx, cy, start, end, inner, outer) => { const point = (angle, radius) => ({ x: cx + Math.cos(angle) * radius, y: cy + Math.sin(angle) * radius }); const a = point(start, inner); const b = point(end, inner); const c = point(end, outer); const d = point(start, outer); const large = end - start > Math.PI ? 1 : 0; return "M" + a.x + " " + a.y + " A" + inner + " " + inner + " 0 " + large + " 1 " + b.x + " " + b.y + " L" + c.x + " " + c.y + " A" + outer + " " + outer + " 0 " + large + " 0 " + d.x + " " + d.y + " Z"; };
  const renderMetroVisual = (viewport, items, primary) => {
    [120, 240, 360, 480, 600, 720].forEach((x) => topologyLine(viewport, "topology-grid-line", x, 150, x, 570));
    topologyLine(viewport, "topology-metro-trunk", 70, 360, 730, 360);
    const trunk = primary || items[0] || null; if (trunk) topologyNode(viewport, items, trunk, 705, 360, -44);
    const branches = trunk ? items.filter((item) => item.id !== trunk.id) : items;
    branches.forEach((item, index) => { const row = Math.floor(index / 4); const upward = index % 2 === 0; const originX = 120 + (index % 4) * 130; const endX = Math.min(720, originX + 170 + row * 14); const endY = upward ? 160 - row * 22 - (index % 4) * 10 : 540 + row * 22 + (index % 4) * 10; const curve = topologyPath(viewport, "topology-metro-branch " + topologyPaletteClass(items, item), "M" + originX + " 360 C" + (originX + 48) + " 360 " + (endX - 58) + " " + endY + " " + endX + " " + endY); curve.setAttribute("data-topology-worktree-edge", item.id); const origin = svg("circle"); origin.setAttribute("class", "topology-metro-station " + topologyPaletteClass(items, item)); origin.setAttribute("cx", String(originX)); origin.setAttribute("cy", "360"); origin.setAttribute("r", "6"); viewport.append(origin); topologyNode(viewport, items, item, endX, endY, upward ? 18 : -42); const pillWidth = Math.max(54, item.state.length * 7 + 18); topologyRect(viewport, "topology-lifecycle-pill " + topologyPaletteClass(items, item), endX - pillWidth / 2, endY + (upward ? -42 : 28), pillWidth, 20, 10); topologyCaption(viewport, "topology-lifecycle-label", item.state, endX, endY + (upward ? -28 : 42), "middle"); });
    topologyCaption(viewport, "topology-caption", "Observed worktrees; curved connectors are explicitly unverified", 70, 675);
  };
  const renderRadarVisual = (viewport, items) => {
    const cx = 400; const cy = 360;
    [52, 104, 156, 208, 260].forEach((radius) => { const ring = svg("circle"); ring.setAttribute("class", "topology-radar-ring"); ring.setAttribute("cx", String(cx)); ring.setAttribute("cy", String(cy)); ring.setAttribute("r", String(radius)); viewport.append(ring); });
    for (let index = 0; index < 6; index += 1) { const angle = index / 6 * Math.PI * 2 - Math.PI / 2; topologyLine(viewport, "topology-radar-axis", cx, cy, cx + Math.cos(angle) * 260, cy + Math.sin(angle) * 260); }
    topologyCaption(viewport, "topology-radar-readout", "SCOPE / OBSERVED", 54, 68); topologyCaption(viewport, "topology-radar-readout", String(items.length).padStart(2, "0") + " WORKTREES", 54, 86);
    items.forEach((item, index) => { const angle = index / Math.max(items.length, 1) * Math.PI * 2 - Math.PI / 2; const distance = item.baseDistance.status === "available" ? Math.min(250, 86 + (item.baseDistance.ahead + item.baseDistance.behind) * 28) : 125 + (index % 3) * 50; topologyNode(viewport, items, item, cx + Math.cos(angle) * distance, cy + Math.sin(angle) * distance, 0, 8); });
    topologyCaption(viewport, "topology-caption", "Radial distance uses observed base distance when available; otherwise placement is illustrative", 70, 686);
  };
  const renderTimelineVisual = (viewport, items, events, drawingHeight) => {
    const times = topologyTimes(events); const axisY = drawingHeight - 74; topologyLine(viewport, "topology-timeline-axis", 190, axisY, 730, axisY);
    for (let index = 0; index <= 5; index += 1) { const x = 190 + index * 108; topologyLine(viewport, "topology-timeline-tick-line", x, 68, x, axisY); if (times.values.length) { const value = times.min + (times.max - times.min) * (index / 5); topologyCaption(viewport, "topology-timeline-tick", new Date(value).toISOString().slice(5, 16).replace("T", " "), x, axisY + 24, "middle"); } }
    items.forEach((item, index) => { const y = 110 + index * 90; const row = topologyInteractiveGroup(viewport, item, "topology-timeline-worktree " + topologyPaletteClass(items, item)); topologyRect(row, "topology-timeline-row-bg", 28, y - 28, 714, 56, 5); topologyCaption(row, "topology-timeline-label", topologyVisualLabel(items, item), 46, y + 4); topologyLine(row, "topology-timeline-row " + topologyPaletteClass(items, item), 190, y, 730, y); const laneEvents = events.filter(({ event }) => event.sessionId === item.owner.sessionId); laneEvents.forEach(({ event }, eventIndex) => { const x = times.x(Date.parse(event.at)); const marker = svg("polygon"); marker.setAttribute("class", "topology-event-marker"); marker.setAttribute("data-topology-palette", String(items.indexOf(item) % 5)); marker.setAttribute("data-topology-event", event.sessionId + "-" + index + "-" + eventIndex); marker.setAttribute("aria-label", event.at + " " + event.kind); marker.setAttribute("points", x + "," + (y - 8) + " " + (x + 8) + "," + y + " " + x + "," + (y + 8) + " " + (x - 8) + "," + y); marker.textContent = event.at + " " + event.kind; row.append(marker); if (eventIndex === laneEvents.length - 1) topologyCaption(row, "topology-event-label", event.at.slice(11, 16) + " " + event.kind, Math.min(x + 12, 630), y - 12); }); if (!laneEvents.length) topologyCaption(row, "topology-unavailable-label", "Unavailable", 205, y + 4); });
    if (!events.length) topologyCaption(viewport, "topology-caption", "Unavailable: no timestamped observed events", 190, axisY - 12); topologyCaption(viewport, "topology-caption", "Only observed timestamps are positioned; lifecycle intervals are never inferred", 28, drawingHeight - 14);
  };
  const renderGitTreeVisual = (viewport, items, primary, drawingHeight) => {
    const trunk = primary || items[0] || null; topologyLine(viewport, "topology-gittree-root", 400, 74, 400, drawingHeight - 72);
    if (trunk) topologyNode(viewport, items, trunk, 400, 92);
    const branches = trunk ? items.filter((item) => item.id !== trunk.id) : items;
    branches.forEach((item, index) => { const column = index % 5; const row = Math.floor(index / 5); const side = column % 2 === 0 ? -1 : 1; const reach = 128 + Math.floor(column / 2) * 82; const x = 400 + side * reach; const y = 170 + row * 110 + column * 76; const originY = 128 + row * 104 + column * 18; const path = topologyPath(viewport, "topology-gittree-branch " + topologyPaletteClass(items, item), "M400 " + originY + " C" + (400 + side * 68) + " " + originY + " " + (x - side * 54) + " " + y + " " + x + " " + y); path.setAttribute("data-topology-worktree-edge", item.id); const split = svg("circle"); split.setAttribute("class", "topology-gittree-split " + topologyPaletteClass(items, item)); split.setAttribute("cx", "400"); split.setAttribute("cy", String(originY)); split.setAttribute("r", "5"); viewport.append(split); topologyNode(viewport, items, item, x, y, side < 0 ? -48 : 18); });
    topologyCaption(viewport, "topology-caption", "Observed worktree relationship only. Commit ancestry and branch points are unavailable.", 70, drawingHeight - 24);
  };
  const renderSunburstVisual = (viewport, items, primary) => {
    const cx = 400; const cy = 360; const branches = primary ? items.filter((item) => item.id !== primary.id) : items; const count = Math.max(branches.length, 1);
    branches.forEach((item, index) => { const start = index / count * Math.PI * 2 - Math.PI / 2 + 0.018; const end = (index + 1) / count * Math.PI * 2 - Math.PI / 2 - 0.018; topologyPath(viewport, "topology-sunburst-sector " + topologyPaletteClass(items, item), topologyAnnularSector(cx, cy, start, end, 72, 242)); const middle = (start + end) / 2; topologyNode(viewport, items, item, cx + Math.cos(middle) * 160, cy + Math.sin(middle) * 160, 0, 8); });
    if (primary) topologyNode(viewport, items, primary, cx, cy, 0, 8); else { const center = svg("circle"); center.setAttribute("class", "topology-sunburst-center"); center.setAttribute("cx", String(cx)); center.setAttribute("cy", String(cy)); center.setAttribute("r", "34"); viewport.append(center); }
    [72, 128, 184, 242].forEach((radius) => { const ring = svg("circle"); ring.setAttribute("class", "topology-sunburst-ring"); ring.setAttribute("cx", String(cx)); ring.setAttribute("cy", String(cy)); ring.setAttribute("r", String(radius)); viewport.append(ring); });
    topologyCaption(viewport, "topology-caption", "Angular ordering is illustrative; rings do not infer lifecycle or ancestry", 70, 686);
  };
  const renderSwimlanesVisual = (viewport, items, events, drawingHeight) => {
    const times = topologyTimes(events); const axisY = drawingHeight - 66; topologyLine(viewport, "topology-timeline-axis", 170, axisY, 730, axisY);
    items.forEach((item, index) => { const y = 110 + index * 90; const row = topologyInteractiveGroup(viewport, item, "topology-swimlane-worktree " + topologyPaletteClass(items, item)); topologyRect(row, "topology-swimlane-row-bg", 18, y - 34, 724, 68, 5); topologyLine(row, "topology-swimlane", 170, y, 730, y); topologyCaption(row, "topology-lane-label", topologyVisualLabel(items, item), 34, y + 4); const laneEvents = events.filter(({ event }) => event.sessionId === item.owner.sessionId); laneEvents.forEach(({ event }, eventIndex) => { const x = times.x(Date.parse(event.at)); const marker = svg("polygon"); marker.setAttribute("class", "topology-event-marker"); marker.setAttribute("data-topology-palette", String(items.indexOf(item) % 5)); marker.setAttribute("data-topology-event", event.sessionId + "-" + index + "-" + eventIndex); marker.setAttribute("aria-label", event.at + " " + event.kind); marker.setAttribute("points", x + "," + (y - 8) + " " + (x + 8) + "," + y + " " + x + "," + (y + 8) + " " + (x - 8) + "," + y); marker.textContent = event.at + " " + event.kind; row.append(marker); if (eventIndex === laneEvents.length - 1) topologyCaption(row, "topology-event-label", event.at.slice(11, 16) + " " + event.kind, Math.min(x + 12, 630), y - 11); }); });
    if (times.values.length) for (let index = 0; index <= 5; index += 1) { const value = times.min + (times.max - times.min) * (index / 5); topologyCaption(viewport, "topology-timeline-tick", new Date(value).toISOString().slice(5, 16).replace("T", " "), 170 + index * 112, axisY + 24, "middle"); } else topologyCaption(viewport, "topology-caption", "Unavailable: no timestamped observed events", 170, drawingHeight - 24);
  };
  const topologyVisual = () => {
    const items = topology.worktrees || []; const drawingHeight = topologyMode === "swimlanes" || topologyMode === "timeline" ? Math.max(720, items.length * 90 + 150) : topologyMode === "gittree" ? Math.max(720, Math.ceil(Math.max(items.length - 1, 0) / 5) * 110 + 470) : 720;
    const stage = document.createElement("div"); stage.id = "topology-stage"; stage.className = "topology-stage topology-stage-" + topologyMode; if (topologyMode === "terminal") { stage.append(topologyText()); return stage; }
    const drawing = svg("svg"); drawing.setAttribute("class", "topology-drawing topology-drawing-" + topologyMode); drawing.setAttribute("viewBox", "0 0 800 " + drawingHeight); drawing.setAttribute("width", "800"); drawing.setAttribute("height", String(drawingHeight)); drawing.setAttribute("role", "group"); drawing.setAttribute("aria-label", topologyMode + " observed worktrees. Relationships are unverified.");
    const viewport = topologyViewport(drawing); const primary = items.find((item) => item.id === topology.primaryWorktreeId) || null; const events = observedEvents().filter(({ event }) => event.at);
    if (topologyMode === "metro") renderMetroVisual(viewport, items, primary);
    if (topologyMode === "radar") renderRadarVisual(viewport, items);
    if (topologyMode === "timeline") renderTimelineVisual(viewport, items, events, drawingHeight);
    if (topologyMode === "gittree") renderGitTreeVisual(viewport, items, primary, drawingHeight);
    if (topologyMode === "sunburst") renderSunburstVisual(viewport, items, primary);
    if (topologyMode === "swimlanes") renderSwimlanesVisual(viewport, items, events, drawingHeight);
    if (panModes.includes(topologyMode)) { let lastX = 0; let lastY = 0; let dragging = false; const updateViewport = () => viewport.setAttribute("transform", "translate(" + topologyX + "," + topologyY + ") scale(" + topologyScale + ")"); const stopDragging = () => { dragging = false; }; stage.setAttribute("tabindex", "0"); stage.setAttribute("role", "group"); stage.setAttribute("aria-label", "Pan " + topologyMode + " topology with arrow keys. Home or 0 resets the view."); stage.addEventListener("wheel", (event) => { event.preventDefault(); topologyScale = Math.max(0.4, Math.min(4, topologyScale * (event.deltaY < 0 ? 1.12 : 0.89))); updateViewport(); }); stage.addEventListener("keydown", (event) => { const step = 24; if (event.key === "Home" || event.key === "0") { topologyX = 0; topologyY = 0; topologyScale = 1; } else if (event.key === "ArrowRight") topologyX = Math.max(-300, Math.min(300, topologyX + step)); else if (event.key === "ArrowLeft") topologyX = Math.max(-300, Math.min(300, topologyX - step)); else if (event.key === "ArrowDown") topologyY = Math.max(-200, Math.min(200, topologyY + step)); else if (event.key === "ArrowUp") topologyY = Math.max(-200, Math.min(200, topologyY - step)); else return; event.preventDefault(); updateViewport(); }); stage.addEventListener("pointerdown", (event) => { dragging = true; lastX = event.clientX; lastY = event.clientY; }); stage.addEventListener("pointermove", (event) => { if (!dragging) return; topologyX = Math.max(-300, Math.min(300, topologyX + event.clientX - lastX)); topologyY = Math.max(-200, Math.min(200, topologyY + event.clientY - lastY)); lastX = event.clientX; lastY = event.clientY; updateViewport(); }); stage.addEventListener("pointerup", stopDragging); stage.addEventListener("pointercancel", stopDragging); }
    const selected = selectionCommitted ? items.find((item) => item.id === selectedId) : null; if (selected) { const identity = document.createElement("p"); identity.className = "topology-selected"; identity.textContent = "Selected " + topologyVisualLabel(items, selected) + ": " + label(selected) + " at " + selected.path; stage.append(drawing, identity); } else stage.append(drawing); return stage;
  };
  const topologyAlternative = () => { const details = document.createElement("details"); details.className = "topology-alternative"; details.setAttribute("data-topology-alternative", "observed-worktree-records"); details.open = false; const summary = document.createElement("summary"); summary.textContent = "Observed worktree and event records"; details.append(summary, topologyText()); return details; };
`;
