import path from "node:path";

export function emptyDeletePreflight(
  repoRoot: string,
  mode: unknown,
  deleteRequestedBranch: boolean,
  abandonUnmerged: boolean,
  allowIgnoredFiles: boolean,
  allowRedundantDirtyPaths: boolean,
): Record<string, unknown> {
  return {
    repoRoot: path.resolve(repoRoot),
    mode,
    targetKind: null,
    targetPath: null,
    worktreeListed: null,
    branch: null,
    head: null,
    detached: false,
    sessionId: null,
    sessionStatus: "unrecorded",
    sessionRecorded: false,
    deleteBranch: deleteRequestedBranch,
    abandonUnmerged,
    ancestryRef: null,
    ancestryProven: null,
    unmergedCommits: [],
    unmergedCommitCount: 0,
    allowIgnoredFiles,
    allowRedundantDirtyPaths,
    archivePath: null,
    archiveSha256: null,
    archivedPaths: [],
    archivedPathProofs: [],
    archivedPathCount: 0,
    cleanedArchivedPaths: [],
    cleanedArchivedPathCount: 0,
    baseRef: null,
    baseRefOid: null,
    dirtyFiles: [],
    dirtyFileCount: 0,
    redundantDirtyProofs: [],
    redundantDirtyFileCount: 0,
    dirtySnapshotCommit: null,
    dirtySnapshotRef: null,
    dirtySnapshotFileCount: 0,
    dirtySnapshotFiles: [],
    cleanedDirtyFiles: [],
    cleanedDirtyFileCount: 0,
    ignoredFiles: [],
    ignoredFileCount: 0,
    stashCount: 0,
    safetyRef: null,
    blockers: [],
  };
}
